### ISSUE TITLE
Create a blacklist using the "server" option in the conf file for dnsmasq

### ISSUE THREAD

**Issue by savyajha** [oznu/dns-zone-blacklist#1]
The current way of making the blocklist makes it such that the entries use the "address" option. It is quite easy to make a blocklist using the "server" as well from it in [this way](https://pgl.yoyo.org/as/serverlist.php?hostformat=dnsmasq-server&showintro=1&startdate%5Bday%5D=&startdate%5Bmonth%5D=&startdate%5Byear%5D=) as well. This has the added advantage of dnsmasq responding with "NX Domain", causing the browser to not even attempt a lookup.

**Comment by oznu** [comment]
Thanks.

Created an alternative dnsmasq format:

https://raw.githubusercontent.com/oznu/dns-zone-blacklist/master/dnsmasq/dnsmasq-server.blacklist
