### ISSUE TITLE
hosts file

### ISSUE THREAD

**Issue by sido420** [oznu/dns-zone-blacklist#11]
In addition to DNS zone files, can you also add functionality to generate hosts file? It shouldn't be too hard I believe. The use-case is for personal computers.

The other project StevenBlack/hosts where you collect data from uses python. 

Also, does this project include data from all sources mentioned in https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants?

**Comment by bahirul** [comment]
@sido420 you can try my script for generating hosts file, pihole, and bind rpz format.

https://github.com/bahirul/dns-blacklist

**Comment by oznu** [comment]
The source data is a hosts file, so it doesn't make much sense to convert it back to a hosts file.
