### ISSUE TITLE
lib.rus.ec

### ISSUE THREAD

**Issue by kravietz** [oznu/dns-zone-blacklist#14]
The whole domain `lib.rus.ec` is being blocked. This is domain of the Library Genesis project at http://gen.lib.rus.ec/ which aims at giving free access to scientific research. It is controversial as it violates copyright of large publishers, but otherwise does not publish malware etc so unless this blacklist aims at piracy prevention this one should be whitelisted.

**Comment by kravietz** [comment]
```
$  curl -s --compressed https://raw.githubusercontent.com/oznu/dns-zone-blacklist/master/unbound/unbound-nxdomain.blacklist | grep lib.rus.ec
local-zone: "lib.rus.ec" static
```

**Comment by oznu** [comment]
Hi @kravietz 

This project does not maintain a blacklist (that would be far to much effort!), it's taken directly from this repo instead: https://github.com/StevenBlack/hosts
