### ISSUE TITLE
Please remove az416426.vo.msecnd.net 

### ISSUE THREAD

**Issue by Z6543** [oznu/dns-zone-blacklist#15]
Hi! 
One of the VPNs I use at a partner company is using az416426.vo.msecnd.net in their VPN login process. If this host is blocked, I cannot login to the VPN. 

Can you please remove this host from the blacklist? 
I believe removing this entry from the list could help others facing similar issues.

**Comment by darkpixel** [comment]
Maybe you could just add it to your custom whitelist file and rebuild your list?

https://github.com/oznu/dns-zone-blacklist/blob/master/custom.whitelist.json

**Comment by oznu** [comment]
Hi @Z6543,

The list is maintained here: https://github.com/StevenBlack/hosts
