### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by hashworks** [oznu/dns-zone-blacklist#16]
Hi,

could you add a license you want to use? Maybe MIT since [StevenBlack/hosts](https://github.com/StevenBlack/hosts/blob/master/license.txt) uses that. Otherwise [Unlicense](https://unlicense.org/) is possible as well.

**Comment by hashworks** [comment]
Nevermind, I just noted you specified `MIT` in your [`package.json`](https://github.com/oznu/dns-zone-blacklist/blob/master/package.json#L10).

**Comment by hashworks** [comment]
@oznu I'll have to reopen this since we do need a valid LICENSE file for the [AUR](https://aur.archlinux.org/packages/dns-zone-blacklist-git/).

**Comment by oznu** [comment]
Thanks
