### ISSUE TITLE
Remove/whitelist catchall for *.info TLD

### ISSUE THREAD

**Issue by fuxii** [oznu/dns-zone-blacklist#24]
The latest bind file contains a catchall for the .info TLD. Would it be possible to remove/whitelist that TLD for the automated builds?

**Comment by oznu** [comment]
Done, thanks for reporting.

The build task will now check against a known list of TLDs.

**Comment by fuxii** [comment]
A general solution is even better. Thank you for the fast fix!

**Comment by oznu** [comment]
I'd actually noticed a .info domain I visit wasn't working on the local network, I hadn't investigated the issue yet though 😄
